{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>temperaturemin</th>\n",
       "      <th>temperaturemax</th>\n",
       "      <th>precipitation</th>\n",
       "      <th>snowfall</th>\n",
       "      <th>snowdepth</th>\n",
       "      <th>avgwindspeed</th>\n",
       "      <th>fastest2minwinddir</th>\n",
       "      <th>fastest2minwindspeed</th>\n",
       "      <th>fastest5secwinddir</th>\n",
       "      <th>...</th>\n",
       "      <th>drizzle</th>\n",
       "      <th>snow</th>\n",
       "      <th>freezingrain</th>\n",
       "      <th>smokehaze</th>\n",
       "      <th>thunder</th>\n",
       "      <th>highwind</th>\n",
       "      <th>hail</th>\n",
       "      <th>blowingsnow</th>\n",
       "      <th>dust</th>\n",
       "      <th>freezingfog</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2009-10-03</td>\n",
       "      <td>55.0</td>\n",
       "      <td>82.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2.91</td>\n",
       "      <td>240.0</td>\n",
       "      <td>16.11</td>\n",
       "      <td>230.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2009-10-10</td>\n",
       "      <td>59.0</td>\n",
       "      <td>79.0</td>\n",
       "      <td>0.02</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>7.83</td>\n",
       "      <td>220.0</td>\n",
       "      <td>17.00</td>\n",
       "      <td>220.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2009-10-14</td>\n",
       "      <td>46.9</td>\n",
       "      <td>61.0</td>\n",
       "      <td>0.14</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>8.72</td>\n",
       "      <td>40.0</td>\n",
       "      <td>14.99</td>\n",
       "      <td>50.0</td>\n",
       "      <td>...</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2009-10-17</td>\n",
       "      <td>45.0</td>\n",
       "      <td>57.9</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.26</td>\n",
       "      <td>30.0</td>\n",
       "      <td>14.09</td>\n",
       "      <td>40.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2009-10-29</td>\n",
       "      <td>48.0</td>\n",
       "      <td>68.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>5.82</td>\n",
       "      <td>80.0</td>\n",
       "      <td>14.99</td>\n",
       "      <td>70.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>2009-11-03</td>\n",
       "      <td>37.9</td>\n",
       "      <td>71.1</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2.01</td>\n",
       "      <td>20.0</td>\n",
       "      <td>8.05</td>\n",
       "      <td>290.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>2009-11-10</td>\n",
       "      <td>55.9</td>\n",
       "      <td>63.0</td>\n",
       "      <td>0.88</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.70</td>\n",
       "      <td>30.0</td>\n",
       "      <td>16.11</td>\n",
       "      <td>30.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>2009-11-16</td>\n",
       "      <td>42.1</td>\n",
       "      <td>73.9</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.89</td>\n",
       "      <td>80.0</td>\n",
       "      <td>8.05</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>2009-11-17</td>\n",
       "      <td>46.9</td>\n",
       "      <td>63.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>5.82</td>\n",
       "      <td>50.0</td>\n",
       "      <td>14.09</td>\n",
       "      <td>50.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>2009-11-18</td>\n",
       "      <td>52.0</td>\n",
       "      <td>62.1</td>\n",
       "      <td>0.45</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>8.28</td>\n",
       "      <td>40.0</td>\n",
       "      <td>16.11</td>\n",
       "      <td>50.0</td>\n",
       "      <td>...</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>2009-11-19</td>\n",
       "      <td>57.9</td>\n",
       "      <td>73.0</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>5.14</td>\n",
       "      <td>250.0</td>\n",
       "      <td>10.07</td>\n",
       "      <td>250.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>2009-11-22</td>\n",
       "      <td>37.0</td>\n",
       "      <td>57.0</td>\n",
       "      <td>0.19</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>5.82</td>\n",
       "      <td>70.0</td>\n",
       "      <td>17.00</td>\n",
       "      <td>70.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>2009-11-27</td>\n",
       "      <td>36.0</td>\n",
       "      <td>54.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>7.38</td>\n",
       "      <td>250.0</td>\n",
       "      <td>21.03</td>\n",
       "      <td>270.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>2009-12-01</td>\n",
       "      <td>30.0</td>\n",
       "      <td>55.9</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2.01</td>\n",
       "      <td>240.0</td>\n",
       "      <td>8.05</td>\n",
       "      <td>230.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>2009-12-08</td>\n",
       "      <td>33.1</td>\n",
       "      <td>46.0</td>\n",
       "      <td>0.45</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.49</td>\n",
       "      <td>80.0</td>\n",
       "      <td>16.11</td>\n",
       "      <td>80.0</td>\n",
       "      <td>...</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>2009-12-11</td>\n",
       "      <td>25.0</td>\n",
       "      <td>36.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3.36</td>\n",
       "      <td>290.0</td>\n",
       "      <td>12.08</td>\n",
       "      <td>290.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>2009-12-16</td>\n",
       "      <td>28.9</td>\n",
       "      <td>48.9</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2.91</td>\n",
       "      <td>10.0</td>\n",
       "      <td>10.07</td>\n",
       "      <td>350.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>2009-12-17</td>\n",
       "      <td>28.0</td>\n",
       "      <td>45.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2.01</td>\n",
       "      <td>50.0</td>\n",
       "      <td>10.07</td>\n",
       "      <td>20.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>2009-12-21</td>\n",
       "      <td>24.1</td>\n",
       "      <td>48.9</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2.24</td>\n",
       "      <td>240.0</td>\n",
       "      <td>14.09</td>\n",
       "      <td>270.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>2009-12-23</td>\n",
       "      <td>25.0</td>\n",
       "      <td>53.1</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.45</td>\n",
       "      <td>50.0</td>\n",
       "      <td>6.04</td>\n",
       "      <td>160.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>2010-01-07</td>\n",
       "      <td>19.9</td>\n",
       "      <td>48.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>5.37</td>\n",
       "      <td>210.0</td>\n",
       "      <td>12.97</td>\n",
       "      <td>230.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>2010-01-08</td>\n",
       "      <td>21.9</td>\n",
       "      <td>42.1</td>\n",
       "      <td>0.05</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>8.95</td>\n",
       "      <td>240.0</td>\n",
       "      <td>23.04</td>\n",
       "      <td>230.0</td>\n",
       "      <td>...</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>2010-01-10</td>\n",
       "      <td>19.0</td>\n",
       "      <td>37.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2.46</td>\n",
       "      <td>30.0</td>\n",
       "      <td>12.08</td>\n",
       "      <td>30.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>2010-01-14</td>\n",
       "      <td>23.0</td>\n",
       "      <td>57.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3.58</td>\n",
       "      <td>220.0</td>\n",
       "      <td>8.95</td>\n",
       "      <td>220.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>2010-01-19</td>\n",
       "      <td>35.1</td>\n",
       "      <td>66.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1.79</td>\n",
       "      <td>240.0</td>\n",
       "      <td>12.08</td>\n",
       "      <td>230.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>2010-02-16</td>\n",
       "      <td>27.0</td>\n",
       "      <td>41.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>7.61</td>\n",
       "      <td>240.0</td>\n",
       "      <td>17.90</td>\n",
       "      <td>230.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>2010-02-20</td>\n",
       "      <td>23.0</td>\n",
       "      <td>59.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2.46</td>\n",
       "      <td>280.0</td>\n",
       "      <td>12.08</td>\n",
       "      <td>290.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>2010-02-22</td>\n",
       "      <td>36.0</td>\n",
       "      <td>52.0</td>\n",
       "      <td>0.29</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2.46</td>\n",
       "      <td>110.0</td>\n",
       "      <td>16.11</td>\n",
       "      <td>110.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>2010-03-02</td>\n",
       "      <td>33.1</td>\n",
       "      <td>42.1</td>\n",
       "      <td>0.29</td>\n",
       "      <td>0.2</td>\n",
       "      <td>0.0</td>\n",
       "      <td>9.62</td>\n",
       "      <td>50.0</td>\n",
       "      <td>19.91</td>\n",
       "      <td>10.0</td>\n",
       "      <td>...</td>\n",
       "      <td>Yes</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>2010-03-09</td>\n",
       "      <td>35.1</td>\n",
       "      <td>73.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2.01</td>\n",
       "      <td>230.0</td>\n",
       "      <td>14.09</td>\n",
       "      <td>220.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4282</th>\n",
       "      <td>2012-03-07</td>\n",
       "      <td>34.0</td>\n",
       "      <td>70.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>7.16</td>\n",
       "      <td>220.0</td>\n",
       "      <td>19.91</td>\n",
       "      <td>210.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4283</th>\n",
       "      <td>2012-03-12</td>\n",
       "      <td>42.1</td>\n",
       "      <td>73.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>8.28</td>\n",
       "      <td>220.0</td>\n",
       "      <td>19.91</td>\n",
       "      <td>240.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4284</th>\n",
       "      <td>2012-03-26</td>\n",
       "      <td>53.1</td>\n",
       "      <td>77.0</td>\n",
       "      <td>0.03</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>5.82</td>\n",
       "      <td>40.0</td>\n",
       "      <td>17.90</td>\n",
       "      <td>40.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4285</th>\n",
       "      <td>2012-03-29</td>\n",
       "      <td>55.9</td>\n",
       "      <td>82.9</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.04</td>\n",
       "      <td>280.0</td>\n",
       "      <td>17.00</td>\n",
       "      <td>280.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4286</th>\n",
       "      <td>2012-03-31</td>\n",
       "      <td>59.0</td>\n",
       "      <td>75.9</td>\n",
       "      <td>0.27</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.26</td>\n",
       "      <td>80.0</td>\n",
       "      <td>17.90</td>\n",
       "      <td>80.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4287</th>\n",
       "      <td>2012-04-06</td>\n",
       "      <td>39.9</td>\n",
       "      <td>63.0</td>\n",
       "      <td>0.05</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.93</td>\n",
       "      <td>40.0</td>\n",
       "      <td>19.91</td>\n",
       "      <td>20.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4288</th>\n",
       "      <td>2012-04-21</td>\n",
       "      <td>55.0</td>\n",
       "      <td>80.1</td>\n",
       "      <td>0.24</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>5.82</td>\n",
       "      <td>20.0</td>\n",
       "      <td>14.99</td>\n",
       "      <td>200.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4289</th>\n",
       "      <td>2012-04-22</td>\n",
       "      <td>48.0</td>\n",
       "      <td>62.1</td>\n",
       "      <td>0.82</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>8.28</td>\n",
       "      <td>50.0</td>\n",
       "      <td>17.00</td>\n",
       "      <td>30.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4290</th>\n",
       "      <td>2012-04-23</td>\n",
       "      <td>39.9</td>\n",
       "      <td>51.1</td>\n",
       "      <td>0.01</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.71</td>\n",
       "      <td>290.0</td>\n",
       "      <td>17.00</td>\n",
       "      <td>290.0</td>\n",
       "      <td>...</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4291</th>\n",
       "      <td>2012-04-25</td>\n",
       "      <td>39.9</td>\n",
       "      <td>68.0</td>\n",
       "      <td>0.03</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.71</td>\n",
       "      <td>230.0</td>\n",
       "      <td>17.90</td>\n",
       "      <td>240.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4292</th>\n",
       "      <td>2012-05-11</td>\n",
       "      <td>46.9</td>\n",
       "      <td>73.9</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2.46</td>\n",
       "      <td>40.0</td>\n",
       "      <td>12.97</td>\n",
       "      <td>30.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4293</th>\n",
       "      <td>2012-05-19</td>\n",
       "      <td>54.0</td>\n",
       "      <td>77.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.04</td>\n",
       "      <td>40.0</td>\n",
       "      <td>17.90</td>\n",
       "      <td>50.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4294</th>\n",
       "      <td>2012-05-26</td>\n",
       "      <td>66.0</td>\n",
       "      <td>86.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.93</td>\n",
       "      <td>80.0</td>\n",
       "      <td>14.99</td>\n",
       "      <td>80.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4295</th>\n",
       "      <td>2012-05-28</td>\n",
       "      <td>72.0</td>\n",
       "      <td>90.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.70</td>\n",
       "      <td>200.0</td>\n",
       "      <td>23.04</td>\n",
       "      <td>200.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4296</th>\n",
       "      <td>2012-05-30</td>\n",
       "      <td>64.0</td>\n",
       "      <td>82.0</td>\n",
       "      <td>0.39</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.70</td>\n",
       "      <td>30.0</td>\n",
       "      <td>17.00</td>\n",
       "      <td>30.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4297</th>\n",
       "      <td>2012-06-04</td>\n",
       "      <td>61.0</td>\n",
       "      <td>82.9</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.92</td>\n",
       "      <td>280.0</td>\n",
       "      <td>14.99</td>\n",
       "      <td>290.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4298</th>\n",
       "      <td>2012-06-06</td>\n",
       "      <td>57.0</td>\n",
       "      <td>73.9</td>\n",
       "      <td>0.04</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.47</td>\n",
       "      <td>100.0</td>\n",
       "      <td>12.97</td>\n",
       "      <td>90.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4299</th>\n",
       "      <td>2012-06-07</td>\n",
       "      <td>54.0</td>\n",
       "      <td>81.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1.12</td>\n",
       "      <td>250.0</td>\n",
       "      <td>8.05</td>\n",
       "      <td>240.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4300</th>\n",
       "      <td>2012-06-08</td>\n",
       "      <td>57.0</td>\n",
       "      <td>84.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2.24</td>\n",
       "      <td>40.0</td>\n",
       "      <td>12.08</td>\n",
       "      <td>20.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4301</th>\n",
       "      <td>2012-06-09</td>\n",
       "      <td>57.0</td>\n",
       "      <td>89.1</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.70</td>\n",
       "      <td>230.0</td>\n",
       "      <td>14.99</td>\n",
       "      <td>230.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4302</th>\n",
       "      <td>2012-06-11</td>\n",
       "      <td>71.1</td>\n",
       "      <td>84.0</td>\n",
       "      <td>1.06</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>7.38</td>\n",
       "      <td>200.0</td>\n",
       "      <td>17.00</td>\n",
       "      <td>210.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4303</th>\n",
       "      <td>2012-06-14</td>\n",
       "      <td>57.0</td>\n",
       "      <td>79.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.71</td>\n",
       "      <td>50.0</td>\n",
       "      <td>17.00</td>\n",
       "      <td>40.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4304</th>\n",
       "      <td>2012-06-20</td>\n",
       "      <td>69.1</td>\n",
       "      <td>93.9</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3.13</td>\n",
       "      <td>160.0</td>\n",
       "      <td>12.08</td>\n",
       "      <td>150.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4305</th>\n",
       "      <td>2012-06-26</td>\n",
       "      <td>61.0</td>\n",
       "      <td>81.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.93</td>\n",
       "      <td>50.0</td>\n",
       "      <td>17.90</td>\n",
       "      <td>40.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4306</th>\n",
       "      <td>2012-06-29</td>\n",
       "      <td>71.1</td>\n",
       "      <td>105.1</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>5.82</td>\n",
       "      <td>350.0</td>\n",
       "      <td>23.04</td>\n",
       "      <td>330.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4307</th>\n",
       "      <td>2012-07-07</td>\n",
       "      <td>72.0</td>\n",
       "      <td>102.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>6.26</td>\n",
       "      <td>240.0</td>\n",
       "      <td>17.90</td>\n",
       "      <td>230.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4308</th>\n",
       "      <td>2012-07-12</td>\n",
       "      <td>69.1</td>\n",
       "      <td>82.9</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.03</td>\n",
       "      <td>70.0</td>\n",
       "      <td>8.05</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4309</th>\n",
       "      <td>2012-07-14</td>\n",
       "      <td>73.9</td>\n",
       "      <td>91.9</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.47</td>\n",
       "      <td>160.0</td>\n",
       "      <td>8.05</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4310</th>\n",
       "      <td>2012-07-16</td>\n",
       "      <td>73.9</td>\n",
       "      <td>96.1</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>7.38</td>\n",
       "      <td>230.0</td>\n",
       "      <td>14.99</td>\n",
       "      <td>220.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4311</th>\n",
       "      <td>2012-07-18</td>\n",
       "      <td>75.0</td>\n",
       "      <td>98.1</td>\n",
       "      <td>0.00</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>8.50</td>\n",
       "      <td>220.0</td>\n",
       "      <td>17.00</td>\n",
       "      <td>240.0</td>\n",
       "      <td>...</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>Yes</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "      <td>No</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>4312 rows × 28 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "            date  temperaturemin  temperaturemax  precipitation  snowfall  \\\n",
       "0     2009-10-03            55.0            82.0           0.00       0.0   \n",
       "1     2009-10-10            59.0            79.0           0.02       0.0   \n",
       "2     2009-10-14            46.9            61.0           0.14       0.0   \n",
       "3     2009-10-17            45.0            57.9           0.00       0.0   \n",
       "4     2009-10-29            48.0            68.0           0.00       0.0   \n",
       "5     2009-11-03            37.9            71.1           0.00       0.0   \n",
       "6     2009-11-10            55.9            63.0           0.88       0.0   \n",
       "7     2009-11-16            42.1            73.9           0.00       0.0   \n",
       "8     2009-11-17            46.9            63.0           0.00       0.0   \n",
       "9     2009-11-18            52.0            62.1           0.45       0.0   \n",
       "10    2009-11-19            57.9            73.0           0.01       0.0   \n",
       "11    2009-11-22            37.0            57.0           0.19       0.0   \n",
       "12    2009-11-27            36.0            54.0           0.00       0.0   \n",
       "13    2009-12-01            30.0            55.9           0.00       0.0   \n",
       "14    2009-12-08            33.1            46.0           0.45       0.0   \n",
       "15    2009-12-11            25.0            36.0           0.00       0.0   \n",
       "16    2009-12-16            28.9            48.9           0.00       0.0   \n",
       "17    2009-12-17            28.0            45.0           0.00       0.0   \n",
       "18    2009-12-21            24.1            48.9           0.00       0.0   \n",
       "19    2009-12-23            25.0            53.1           0.00       0.0   \n",
       "20    2010-01-07            19.9            48.0           0.00       0.0   \n",
       "21    2010-01-08            21.9            42.1           0.05       0.0   \n",
       "22    2010-01-10            19.0            37.0           0.00       0.0   \n",
       "23    2010-01-14            23.0            57.0           0.00       0.0   \n",
       "24    2010-01-19            35.1            66.0           0.00       0.0   \n",
       "25    2010-02-16            27.0            41.0           0.00       0.0   \n",
       "26    2010-02-20            23.0            59.0           0.00       0.0   \n",
       "27    2010-02-22            36.0            52.0           0.29       0.0   \n",
       "28    2010-03-02            33.1            42.1           0.29       0.2   \n",
       "29    2010-03-09            35.1            73.0           0.00       0.0   \n",
       "...          ...             ...             ...            ...       ...   \n",
       "4282  2012-03-07            34.0            70.0           0.00       0.0   \n",
       "4283  2012-03-12            42.1            73.0           0.00       0.0   \n",
       "4284  2012-03-26            53.1            77.0           0.03       0.0   \n",
       "4285  2012-03-29            55.9            82.9           0.00       0.0   \n",
       "4286  2012-03-31            59.0            75.9           0.27       0.0   \n",
       "4287  2012-04-06            39.9            63.0           0.05       0.0   \n",
       "4288  2012-04-21            55.0            80.1           0.24       0.0   \n",
       "4289  2012-04-22            48.0            62.1           0.82       0.0   \n",
       "4290  2012-04-23            39.9            51.1           0.01       0.0   \n",
       "4291  2012-04-25            39.9            68.0           0.03       0.0   \n",
       "4292  2012-05-11            46.9            73.9           0.00       0.0   \n",
       "4293  2012-05-19            54.0            77.0           0.00       0.0   \n",
       "4294  2012-05-26            66.0            86.0           0.00       0.0   \n",
       "4295  2012-05-28            72.0            90.0           0.00       0.0   \n",
       "4296  2012-05-30            64.0            82.0           0.39       0.0   \n",
       "4297  2012-06-04            61.0            82.9           0.00       0.0   \n",
       "4298  2012-06-06            57.0            73.9           0.04       0.0   \n",
       "4299  2012-06-07            54.0            81.0           0.00       0.0   \n",
       "4300  2012-06-08            57.0            84.0           0.00       0.0   \n",
       "4301  2012-06-09            57.0            89.1           0.00       0.0   \n",
       "4302  2012-06-11            71.1            84.0           1.06       0.0   \n",
       "4303  2012-06-14            57.0            79.0           0.00       0.0   \n",
       "4304  2012-06-20            69.1            93.9           0.00       0.0   \n",
       "4305  2012-06-26            61.0            81.0           0.00       0.0   \n",
       "4306  2012-06-29            71.1           105.1           0.00       0.0   \n",
       "4307  2012-07-07            72.0           102.0           0.00       0.0   \n",
       "4308  2012-07-12            69.1            82.9           0.00       0.0   \n",
       "4309  2012-07-14            73.9            91.9           0.00       0.0   \n",
       "4310  2012-07-16            73.9            96.1           0.00       0.0   \n",
       "4311  2012-07-18            75.0            98.1           0.00       0.0   \n",
       "\n",
       "      snowdepth  avgwindspeed  fastest2minwinddir  fastest2minwindspeed  \\\n",
       "0           0.0          2.91               240.0                 16.11   \n",
       "1           0.0          7.83               220.0                 17.00   \n",
       "2           0.0          8.72                40.0                 14.99   \n",
       "3           0.0          6.26                30.0                 14.09   \n",
       "4           0.0          5.82                80.0                 14.99   \n",
       "5           0.0          2.01                20.0                  8.05   \n",
       "6           0.0          4.70                30.0                 16.11   \n",
       "7           0.0          0.89                80.0                  8.05   \n",
       "8           0.0          5.82                50.0                 14.09   \n",
       "9           0.0          8.28                40.0                 16.11   \n",
       "10          0.0          5.14               250.0                 10.07   \n",
       "11          0.0          5.82                70.0                 17.00   \n",
       "12          0.0          7.38               250.0                 21.03   \n",
       "13          0.0          2.01               240.0                  8.05   \n",
       "14          0.0          6.49                80.0                 16.11   \n",
       "15          0.0          3.36               290.0                 12.08   \n",
       "16          0.0          2.91                10.0                 10.07   \n",
       "17          0.0          2.01                50.0                 10.07   \n",
       "18          0.0          2.24               240.0                 14.09   \n",
       "19          0.0          0.45                50.0                  6.04   \n",
       "20          0.0          5.37               210.0                 12.97   \n",
       "21          0.0          8.95               240.0                 23.04   \n",
       "22          0.0          2.46                30.0                 12.08   \n",
       "23          0.0          3.58               220.0                  8.95   \n",
       "24          0.0          1.79               240.0                 12.08   \n",
       "25          0.0          7.61               240.0                 17.90   \n",
       "26          0.0          2.46               280.0                 12.08   \n",
       "27          0.0          2.46               110.0                 16.11   \n",
       "28          0.0          9.62                50.0                 19.91   \n",
       "29          0.0          2.01               230.0                 14.09   \n",
       "...         ...           ...                 ...                   ...   \n",
       "4282        0.0          7.16               220.0                 19.91   \n",
       "4283        0.0          8.28               220.0                 19.91   \n",
       "4284        0.0          5.82                40.0                 17.90   \n",
       "4285        0.0          6.04               280.0                 17.00   \n",
       "4286        0.0          6.26                80.0                 17.90   \n",
       "4287        0.0          6.93                40.0                 19.91   \n",
       "4288        0.0          5.82                20.0                 14.99   \n",
       "4289        0.0          8.28                50.0                 17.00   \n",
       "4290        0.0          6.71               290.0                 17.00   \n",
       "4291        0.0          6.71               230.0                 17.90   \n",
       "4292        0.0          2.46                40.0                 12.97   \n",
       "4293        0.0          6.04                40.0                 17.90   \n",
       "4294        0.0          6.93                80.0                 14.99   \n",
       "4295        0.0          4.70               200.0                 23.04   \n",
       "4296        0.0          4.70                30.0                 17.00   \n",
       "4297        0.0          4.92               280.0                 14.99   \n",
       "4298        0.0          4.47               100.0                 12.97   \n",
       "4299        0.0          1.12               250.0                  8.05   \n",
       "4300        0.0          2.24                40.0                 12.08   \n",
       "4301        0.0          4.70               230.0                 14.99   \n",
       "4302        0.0          7.38               200.0                 17.00   \n",
       "4303        0.0          6.71                50.0                 17.00   \n",
       "4304        0.0          3.13               160.0                 12.08   \n",
       "4305        0.0          6.93                50.0                 17.90   \n",
       "4306        0.0          5.82               350.0                 23.04   \n",
       "4307        0.0          6.26               240.0                 17.90   \n",
       "4308        0.0          4.03                70.0                  8.05   \n",
       "4309        0.0          4.47               160.0                  8.05   \n",
       "4310        0.0          7.38               230.0                 14.99   \n",
       "4311        0.0          8.50               220.0                 17.00   \n",
       "\n",
       "      fastest5secwinddir     ...      drizzle snow freezingrain smokehaze  \\\n",
       "0                  230.0     ...           No   No           No        No   \n",
       "1                  220.0     ...           No   No           No        No   \n",
       "2                   50.0     ...          Yes   No           No        No   \n",
       "3                   40.0     ...           No   No           No        No   \n",
       "4                   70.0     ...           No   No           No        No   \n",
       "5                  290.0     ...           No   No           No        No   \n",
       "6                   30.0     ...           No   No           No        No   \n",
       "7                  100.0     ...           No   No           No        No   \n",
       "8                   50.0     ...           No   No           No        No   \n",
       "9                   50.0     ...          Yes   No           No        No   \n",
       "10                 250.0     ...           No   No           No        No   \n",
       "11                  70.0     ...           No   No           No        No   \n",
       "12                 270.0     ...           No   No           No        No   \n",
       "13                 230.0     ...           No   No           No        No   \n",
       "14                  80.0     ...          Yes   No           No        No   \n",
       "15                 290.0     ...           No   No           No        No   \n",
       "16                 350.0     ...           No   No           No        No   \n",
       "17                  20.0     ...           No   No           No        No   \n",
       "18                 270.0     ...           No   No           No        No   \n",
       "19                 160.0     ...           No   No           No        No   \n",
       "20                 230.0     ...           No   No           No        No   \n",
       "21                 230.0     ...          Yes   No           No        No   \n",
       "22                  30.0     ...           No   No           No        No   \n",
       "23                 220.0     ...           No   No           No        No   \n",
       "24                 230.0     ...           No   No           No        No   \n",
       "25                 230.0     ...           No   No           No        No   \n",
       "26                 290.0     ...           No   No           No        No   \n",
       "27                 110.0     ...           No   No           No        No   \n",
       "28                  10.0     ...          Yes  Yes           No        No   \n",
       "29                 220.0     ...           No   No           No        No   \n",
       "...                  ...     ...          ...  ...          ...       ...   \n",
       "4282               210.0     ...           No   No           No        No   \n",
       "4283               240.0     ...           No   No           No        No   \n",
       "4284                40.0     ...           No   No           No        No   \n",
       "4285               280.0     ...           No   No           No        No   \n",
       "4286                80.0     ...           No   No           No        No   \n",
       "4287                20.0     ...           No   No           No        No   \n",
       "4288               200.0     ...           No   No           No        No   \n",
       "4289                30.0     ...           No   No           No        No   \n",
       "4290               290.0     ...          Yes   No           No        No   \n",
       "4291               240.0     ...           No   No           No        No   \n",
       "4292                30.0     ...           No   No           No        No   \n",
       "4293                50.0     ...           No   No           No        No   \n",
       "4294                80.0     ...           No   No           No        No   \n",
       "4295               200.0     ...           No   No           No        No   \n",
       "4296                30.0     ...           No   No           No        No   \n",
       "4297               290.0     ...           No   No           No        No   \n",
       "4298                90.0     ...           No   No           No        No   \n",
       "4299               240.0     ...           No   No           No        No   \n",
       "4300                20.0     ...           No   No           No        No   \n",
       "4301               230.0     ...           No   No           No        No   \n",
       "4302               210.0     ...           No   No           No        No   \n",
       "4303                40.0     ...           No   No           No        No   \n",
       "4304               150.0     ...           No   No           No        No   \n",
       "4305                40.0     ...           No   No           No        No   \n",
       "4306               330.0     ...           No   No           No        No   \n",
       "4307               230.0     ...           No   No           No        No   \n",
       "4308                 NaN     ...           No   No           No        No   \n",
       "4309                 NaN     ...           No   No           No        No   \n",
       "4310               220.0     ...           No   No           No        No   \n",
       "4311               240.0     ...           No   No           No        No   \n",
       "\n",
       "     thunder highwind hail blowingsnow dust freezingfog  \n",
       "0         No       No   No          No   No          No  \n",
       "1         No       No  Yes          No   No          No  \n",
       "2         No       No  Yes          No   No          No  \n",
       "3         No       No   No          No   No          No  \n",
       "4         No       No   No          No   No          No  \n",
       "5         No       No   No          No   No          No  \n",
       "6         No       No  Yes          No   No          No  \n",
       "7         No       No   No          No   No          No  \n",
       "8         No       No   No          No   No          No  \n",
       "9         No       No  Yes          No   No          No  \n",
       "10        No       No  Yes         Yes   No          No  \n",
       "11        No       No  Yes          No   No          No  \n",
       "12        No       No   No          No   No          No  \n",
       "13        No       No   No          No   No          No  \n",
       "14        No       No  Yes          No   No          No  \n",
       "15        No       No   No          No   No          No  \n",
       "16        No       No   No          No   No          No  \n",
       "17        No       No   No          No   No          No  \n",
       "18        No       No   No          No   No          No  \n",
       "19        No       No   No          No   No          No  \n",
       "20        No       No   No          No   No          No  \n",
       "21        No       No  Yes          No   No          No  \n",
       "22        No       No   No          No   No          No  \n",
       "23        No       No   No          No   No          No  \n",
       "24        No       No   No          No   No          No  \n",
       "25        No       No   No          No   No          No  \n",
       "26        No       No   No          No   No          No  \n",
       "27        No       No  Yes         Yes   No          No  \n",
       "28       Yes       No  Yes          No   No          No  \n",
       "29        No       No   No          No   No          No  \n",
       "...      ...      ...  ...         ...  ...         ...  \n",
       "4282      No       No   No          No   No          No  \n",
       "4283      No       No   No          No   No          No  \n",
       "4284      No       No   No          No   No          No  \n",
       "4285      No       No   No          No   No          No  \n",
       "4286     Yes       No   No          No   No          No  \n",
       "4287      No       No   No          No   No          No  \n",
       "4288      No       No   No          No   No          No  \n",
       "4289      No       No   No          No   No          No  \n",
       "4290      No       No   No          No   No          No  \n",
       "4291      No       No   No          No   No          No  \n",
       "4292      No       No   No          No   No          No  \n",
       "4293      No       No   No          No   No          No  \n",
       "4294      No       No   No          No   No          No  \n",
       "4295      No       No   No          No   No          No  \n",
       "4296      No       No   No          No   No          No  \n",
       "4297      No       No   No          No   No          No  \n",
       "4298      No       No   No          No   No          No  \n",
       "4299      No       No   No          No   No          No  \n",
       "4300      No       No   No          No   No          No  \n",
       "4301      No       No   No          No   No          No  \n",
       "4302      No       No   No          No   No          No  \n",
       "4303      No       No   No          No   No          No  \n",
       "4304      No       No   No          No   No          No  \n",
       "4305      No       No   No          No   No          No  \n",
       "4306      No       No   No          No   No          No  \n",
       "4307      No       No   No          No   No          No  \n",
       "4308      No       No   No          No   No          No  \n",
       "4309      No       No   No          No   No          No  \n",
       "4310      No       No   No          No   No          No  \n",
       "4311     Yes       No   No          No   No          No  \n",
       "\n",
       "[4312 rows x 28 columns]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "df= pd.read_csv(\"/home/sunil/Desktop/python_scripts/weather.csv\", delimiter=';')\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
